### ISSUE TITLE
运行错误：LaTeX3 Error: Command '\FA' already defined!For immediate help type H <return>.

### ISSUE THREAD

**Issue by Leng-bingo** [huajh/awesome-latex-cv#9]
LaTeX3 Error: Command '\FA' already defined!For immediate help type H <return>.

**Comment by rayLemond** [comment]
In file awesome-source-cv.cls, line 120. change 'newfontfamily' to 'setfontfamily'. It works for me.

**Comment by Leng-bingo** [comment]
> In file awesome-source-cv.cls, line 120. change 'newfontfamily' to 'setfontfamily'. It works for me.

thanks，thats ok
